// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Hello from '../src/commands/hello.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['hello'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'hello': Hello
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'hello': {
      name: 'hello',
      description: 'Say hello to someone',
      options: {
        'name': { type: 'z.string.default', required: true, hasDefault: true, default: "World", description: 'Name to greet', short: 'n', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"World"}]}, validator: '(val) => true' },
        'excited': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Add excitement!', short: 'e', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":335,"end":340,"loc":{"start":{"line":12,"column":40,"index":335},"end":{"line":12,"column":45,"index":340}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/hello'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
