name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: wst7/bunli-releaser@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
