name: Release

on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set Nodejs
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Build package
      - name: Build package
        run: bun run build

      # Publish package to npm using OIDC Trusted Publishing
      - name: Publish to npm
        run: npm publish --access public

      # Build standalone binaries
      - name: Build binaries
        run: |
          bun install --os '*' --cpu '*'
          bun run build:all

      - name: Rename binaries
        run: |
          find binaries -type f
          mv binaries/darwin-arm64/cli binaries/gum-darwin-arm64
          mv binaries/darwin-x64/cli binaries/gum-darwin-x64
          mv binaries/linux-arm64/cli binaries/gum-linux-arm64
          mv binaries/linux-x64/cli binaries/gum-linux-x64
          mv binaries/windows-x64/cli.exe binaries/gum-windows-x64.exe

      # Upload standalone binaries to GitHub Release
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files:  |
            binaries/gum-darwin-arm64
            binaries/gum-darwin-x64
            binaries/gum-linux-arm64
            binaries/gum-linux-x64
            binaries/gum-windows-x64.exe