name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Build JS package
      - name: Build package
        run: bun run build

      - name: Build binaries
        run: |
          bun install --os '*' --cpu '*'
          bun run build:all

      # Publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: npm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_REGISTRY: https://npm.pkg.github.com

      # Publish to npm
      - name: Publish to npm
        run: npm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org

          
      # Upload binaries to GitHub Release
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: binaries/*